import turtle
monte=turtle.Turtle()
nonte=turtle.Turtle()
fonte=turtle.Turtle()
monte.setpos(-100,-100)
monte.forward(30)
monte.clear()
nonte.clear()
fonte.clear()
fonte.shape("triangle")
monte.shape("square")